
#RM = rm -rf
RM = del /q

SRCS = ../vdp_package.vhd ../ram.vhd ../vdp_colordec.vhd ../vdp_command.vhd \
        ../vdp_linebuf.vhd ../vdp_doublebuf.vhd ../vdp_graphic123m.vhd \
	   ../vdp_graphic4567.vhd ../vdp_hvcounter.vhd ../vdp_interrupt.vhd \
	   ../vdp_ntsc_pal.vhd ../vdp_register.vhd ../vdp_spinforam.vhd \
	   ../vdp_sprite.vhd ../vdp_ssg.vhd ../vdp_text12.vhd \
	   ../vdp_vga.vhd ../vdp_wait_control.vhd ../vdp.vhd
TB = tb2

include ../../make.inc
